FROM debian:11.1-slim


RUN apt-get -y update && \
  apt-get install -y survex curl debian-keyring debian-archive-keyring apt-transport-https && \
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' >> /etc/apt/trusted.gpg.d/caddy-stable.asc && \
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' >> /etc/apt/sources.list.d/caddy-stable.list && \
  apt-get -y update && \
  apt-get install -y caddy
