name: Build Android APK

on: push

jobs:
  trigger:
    runs-on: ubuntu-20.04
    env:
      GODOT_VERSION: 3.4
      GODOT_RELEASE: stable
      ANDROID_HOME: /home/runner/android-sdk
      ANDROID_INSTALLER: /home/runner/android-sdk-installer
      EDITOR_DATA: /home/runner/work/tunnelvr
    steps:
      - name: Download Godot
        run: |
          wget -O godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64.zip
          unzip godot.zip
          mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 godot
          mkdir -p $EDITOR_DATA
          rm godot.zip
          
      - name: Download Godot export templates
        run: |
          wget -O templates.tpz https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_export_templates.tpz
          unzip templates.tpz
          mkdir -p ${EDITOR_DATA}/templates/${GODOT_VERSION}.${GODOT_RELEASE}/
          mv templates/* $EDITOR_DATA/templates/${GODOT_VERSION}.${GODOT_RELEASE}/
          rm templates.tpz
