name: Build Android APK

on: push

jobs:
  trigger:
    runs-on: ubuntu-20.04
    env:
      GODOT_VERSION: 3.4
      GODOT_RELEASE: stable
      ANDROID_HOME: /home/worker/android-sdk
      ANDROID_INSTALLER: /home/worker/android-sdk-installer
      EXPORT_DATA: /home/worker/work/tunnelvr
    steps:
      - name: Download Godot
        run: |
          wget -O godot.zip https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-${GODOT_RELEASE}.64.zip
          unzip godot.zip
          mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 godot
          mkdir -p $EDITOR_DATA
          rm Godot_v${GODOT_VERSION}-${GODOT_RELEASE}_linux_headless.64.zip
